mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
spring:
  mail:
    # 指定邮件服务器地址
    host: smtp.qq.com
    # 登录账户
    username: ${spring.mail.username}
    # 登录密码
    password: ${spring.mail.password}
    # 端口
    port: ${spring.mail.port}
    # 默认编码
    default-encoding: ${spring.mail.default-encoding}
    # 使用的协议
    protocol: ${spring.mail.protocol}
    # 其他的属性
    properties:
      "mail.smtp.connectiontimeout": ${spring.mail.properties.mail.smtp.connectiontimeout}
      "mail.smtp.timeout": ${spring.mail.properties.mail.smtp.timeout}
      "mail.smtp.writetimeout": ${spring.mail.properties.mail.smtp.writetimeout}
      "mail.smtp.auth": ${spring.mail.properties.mail.smtp.auth}
      "mail.smtp.starttls.enable": ${spring.mail.properties.mail.smtp.starttls.enable}
      "mail.smtp.starttls.required": ${spring.mail.properties.mail.smtp.starttls.required}
  profiles:
    active: dev
  datasource:
    driver-class-name: ${yl-ecosphere.datasource.driver-class-name}
    url: jdbc:mysql://${yl-ecosphere.datasource.host}:${yl-ecosphere.datasource.port}/${yl-ecosphere.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${yl-ecosphere.datasource.username}
    password: ${yl-ecosphere.datasource.password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}

yl-ecosphere:
  jwt:
    # 设置jwt加密时所用的秘钥
    secret-key: qht123
    # 设置jwt过期时间
    ttl-millis: 7200000
  alioss:
    endpoint: ${sky.alioss.endpoint}
    #    access-key-id: ${sky.alioss.access-key-id}
    #    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}
