yl-ecosphere:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost #140.246.119.80
    port: 3306 # 这里指的是数据库的端口号
    database: yl_Ecosphere
    username: root
    password: 123456
  aliOss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    bucket-name: yl-ecosphere
    # key 和 secret 将从环境变量中获取
    # OSS_ACCESS_KEY_ID => OSS_ACCESS_KEY_SECRET