mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
spring:
  mail:
    # 指定邮件服务器地址
    host: smtp.qq.com
    # 登录账户
    username: 2727676635@qq.com
    # 登录密码
    password: wsqepiivergedfhc
    # 端口
    port: 465
    # 默认编码
    default-encoding: UTF-8
    # 使用的协议
    protocol: smtps
    # 其他的属性
    properties:
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 3000
      "mail.smtp.writetimeout": 5000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
  profiles:
    active: dev
  datasource:
    driver-class-name: ${yl-ecosphere.datasource.driver-class-name}
    url: jdbc:mysql://${yl-ecosphere.datasource.host}:${yl-ecosphere.datasource.port}/${yl-ecosphere.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${yl-ecosphere.datasource.username}
    password: ${yl-ecosphere.datasource.password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
yl-ecosphere:
  jwt:
    # 设置jwt加密时所用的秘钥
    secret-key: qht123
    # 设置jwt过期时间
    ttl-millis: 7200000
  alioss:
    endpoint: ${sky.alioss.endpoint}
    #    access-key-id: ${sky.alioss.access-key-id}
    #    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}
