yl-ecosphere:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost #140.246.119.80
    port: 3306 # 这里指的是数据库的端口号
    database: yl_Ecosphere
    username: root
    password: 123456
  aliOss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    bucket-name: yl-ecosphere
    # key 和 secret 将从环境变量中获取
    # OSS_ACCESS_KEY_ID => OSS_ACCESS_KEY_SECRET
spring:
  # 发送邮件配置
  mail:
    # 指定邮件服务器地址
    host: smtp.qq.com
    # 登录账户
    username: 2727676635@qq.com
    # 登录密码
    password: wsqepiivergedfhc
    # 端口
    port: 465
    # 默认编码
    default-encoding: UTF-8
    # 使用的协议
    protocol: smtps
    # 其他的属性
    properties:
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 3000
      "mail.smtp.writetimeout": 5000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
  data:
    redis:
      host: 47.236.251.52
      port: 6379